
name: ci

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
          dotnet-quality: ga

      - name: Build tests
        run: dotnet build Tests/FizzBuzzWhizz.Tests/ --configuration Release

      - name: Run tests
        run: dotnet test Tests/FizzBuzzWhizz.Tests/ --no-build --configuration Release -- --results-directory TestResults/ --report-trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Tests/FizzBuzzWhizz.Tests/TestResults/

  generate-version:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Tag Bump
        id: tab_bump
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.1.0
          DEFAULT_BUMP: patch

    outputs:
      new_version: ${{ steps.tab_bump.outputs.new_tag }}

  package-and-publish-lib:
    runs-on: ubuntu-latest
    needs: generate-version

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
          dotnet-quality: ga

      - name: Generate NuGet package
        run: |
          dotnet pack FizzBuzzWhizz/ \
          --configuration Release \
          -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
          -p:RepositoryUrl=https://github.com/Jodre11/FizzBuzzWhizz \
          -o packages

      - name: Publish NuGet package
        run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.PUSH_NUGET }} --source https://nuget.pkg.github.com/Jodre11/index.json
